export const FETCH_USERS_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USERS_REQUEST_SUCCESSFUL = "FETCH_USER_REQUEST_SUCCESSFUL";
export const FETCH_USERS_REQUEST_FAILURE = "FETCH_USER_REQUEST_FAILURE";
